# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='realtor/')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.IntegerField(blank=True, default='0')),
                ('website', models.URLField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.City')),
                ('managers', models.ManyToManyField(blank=True, related_name='manager_realtor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
