# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='realtor/'),
        ),
    ]
