# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_realtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='realtor',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='realtor',
            name='phone_number',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='realtor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
