# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_realtor_agree_to_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='realtor/'),
            preserve_default=False,
        ),
    ]
