# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0007_realtor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='city',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.City'),
        ),
    ]
