# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('Year', 'Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years')], max_length=300, verbose_name='duration'),
        ),
    ]
