# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(blank=True, default=1, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='property.City'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=300, verbose_name='bathroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=300, verbose_name='bed'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default='', max_length=300, on_delete=django.db.models.deletion.CASCADE, to='property.Category'),
        ),
    ]
