# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20180913_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city/')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='neigborhood/')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='image',
        ),
        migrations.AddField(
            model_name='neighborhoodimage',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.Neighborhood'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.City'),
        ),
    ]
