# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20180913_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(null=True, upload_to='properties/'),
        ),
    ]
