# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-14 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20180914_0802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImage',
            new_name='Images',
        ),
    ]
