# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20180914_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='properties/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image_two',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='properties/'),
            preserve_default=False,
        ),
    ]
