# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20180915_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=20),
        ),
    ]
