# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-16 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20180916_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
